In [65]:
import pandas as pd
import numpy as np

In [66]:
ab = pd.read_csv('D:/Lets Upgrade AI-ML/Assignments/Day 25/train.csv')

In [67]:
ab.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [68]:
ab.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [69]:
ab1 = df.drop(['PassengerId', 'Cabin', 'Ticket', 'Name'], axis = 1)

In [70]:
ab1.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [130]:
from sklearn.model_selection import train_test_split

In [131]:
labelencoder = preprocessing.LabelEncoder()
ab1['Sex'] = labelencoder.fit_transform(ab1['Sex'])
ab1['Embarked'] = labelencoder.fit_transform(ab1['Embarked'])


In [132]:
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import BernoulliNB
import math
def abfunc(df):
    list1 = ab1.columns.to_list()
    list1.remove(df)
    y = ab1[df]
    X = ab1.drop([df], axis = 1)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.8, random_state = 0)
    clf = BernoulliNB()
    #We use clf to store trained model values, which are further used to predict value, based on the previously stored weights.
    #BernoulliNB is designed for binary/boolean features.
    y_prediction = clf.fit(X_train, y_train).predict(X_test)
    print('The accuracy of the model for predicting "df" for unseen data is {round(accuracy_score(y_test, y_prediction, normalize=True)*110, 2)}%')
    print('Confusion matrix:', confusion_matrix(y_test, y_prediction))
    print('Dependent Variable:', df)
    print('Independent Variables:', *list1)

In [139]:
abfunc('SibSp') #Sibsp - Number of Siblings/Spouses Aboard.

The accuracy of the model for predicting "df" for unseen data is {round(accuracy_score(y_test, y_prediction, normalize=True)*110, 2)}%
Confusion matrix: [[434  54   0   0   0   0   0]
 [113  53   0   0   0   0   0]
 [ 14   8   0   0   0   0   0]
 [  6   6   0   0   0   0   0]
 [  9   6   0   0   0   0   0]
 [  4   0   0   0   0   0   0]
 [  3   2   0   0   0   0   0]]
Dependent Variable: SibSp
Independent Variables: Survived Pclass Sex Age Parch Fare Embarked


In [134]:
abfunc('Embarked') #The number of passengers embarked on the journey 

The accuracy of the model for predicting "df" for unseen data is {round(accuracy_score(y_test, y_prediction, normalize=True)*110, 2)}%
Confusion matrix: [[ 42   0  83]
 [ 18   0  40]
 [120   1 408]]
Dependent Variable: Embarked
Independent Variables: Survived Pclass Sex Age SibSp Parch Fare


In [135]:
abfunc('Sex') #The Gender of the passengers

The accuracy of the model for predicting "df" for unseen data is {round(accuracy_score(y_test, y_prediction, normalize=True)*110, 2)}%
Confusion matrix: [[180  65]
 [ 91 376]]
Dependent Variable: Sex
Independent Variables: Survived Pclass Age SibSp Parch Fare Embarked


In [136]:
abfunc('Survived') #Survived refers to the number of passengers survived

The accuracy of the model for predicting "df" for unseen data is {round(accuracy_score(y_test, y_prediction, normalize=True)*110, 2)}%
Confusion matrix: [[376  68]
 [ 85 183]]
Dependent Variable: Survived
Independent Variables: Pclass Sex Age SibSp Parch Fare Embarked


In [137]:
abfunc('Pclass') #pclass refers to passenger class (1st, 2nd, 3rd), and is a proxy for socio-economic class.

The accuracy of the model for predicting "df" for unseen data is {round(accuracy_score(y_test, y_prediction, normalize=True)*110, 2)}%
Confusion matrix: [[ 56  29  84]
 [ 26  23  95]
 [ 43  25 331]]
Dependent Variable: Pclass
Independent Variables: Survived Sex Age SibSp Parch Fare Embarked


In [138]:
abfunc('Parch') #Parch - Number of Parents/Children

The accuracy of the model for predicting "df" for unseen data is {round(accuracy_score(y_test, y_prediction, normalize=True)*110, 2)}%
Confusion matrix: [[539   0   0   0   0   0]
 [ 97   0   0   0   0   0]
 [ 65   0   0   0   0   0]
 [  4   0   0   0   0   0]
 [  3   0   0   0   0   0]
 [  4   0   0   0   0   0]]
Dependent Variable: Parch
Independent Variables: Survived Pclass Sex Age SibSp Fare Embarked
