# Day 14&15

# 1. Create a 3x3x3 array with random values 

In [6]:
import numpy as np
import random
arr=np.random.randint(30,size=(3,3,3))
print(arr)

[[[20  1  8]
  [ 6 23  3]
  [26 28  8]]

 [[ 5  3 27]
  [15 21 19]
  [19 18 20]]

 [[27 15 10]
  [22  2 12]
  [26 19  4]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [5]:
import numpy as np
array=np.zeros((5,5))
np.diag([1,2,3,4],-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [6]:
import numpy as np
b=np.zeros((8,8))
b[1::2,::2]=1
b[::2,1::2]=1
print("Checkboard pattern-")
print(b)


Checkboard pattern-
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [18]:
import numpy as np
import random
array1 = np.random.rand(5,5)
print("Matrix")
print(array1)
normalized_matrix = (array1 - np.min(array1))/np.ptp(array1)
print("Normalized Matrix-")
print(normalized)

Matrix
[[0.6495752  0.71402844 0.36118232 0.35573167 0.1944431 ]
 [0.47455854 0.08094733 0.29515613 0.18653662 0.13050015]
 [0.65446355 0.0944884  0.57730627 0.73614395 0.53192611]
 [0.82325409 0.98867359 0.15593289 0.15436579 0.3367303 ]
 [0.42771214 0.68465208 0.85557818 0.4094525  0.22819112]]
Normalized Matrix-
[[0.67200112 0.47236425 0.         0.12135566 0.41088304]
 [0.726589   0.65352808 0.9890505  0.71041057 1.        ]
 [0.25150947 0.9006425  0.1497638  0.26758273 0.09990485]
 [0.85590388 0.77330515 0.66360037 0.84986923 0.73212798]
 [0.88725843 0.71843394 0.08482465 0.80860381 0.25768923]]


# 5.  How to find common values between two arrays?

In [27]:
import numpy as np
array1=[5,6,7,8,9]
print("Array 1-", array1)
array2=[1,2,3,6,7]
print("Array 2-", array2)
print("Common values between Array1 and Array2-")
print(np.intersect1d(array1, array2))


Array 1- [5, 6, 7, 8, 9]
Array 2- [1, 2, 3, 6, 7]
Common values between Array1 and Array2-
[6 7]


# 6.How to get the dates of yesterday, today and tomorrow?

In [28]:
import numpy as np
Yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-29
Today:  2020-07-30
Tomorrow:  2020-07-31


# 7. Consider two random array A and B, check if they are equal

In [17]:
import numpy as np
A = np.array([1,2,3,4,5])
print("First array:", A)
B = np.array([1,2,3,4,4])
print("Second array:", B)
print("Arrays equal or not-")
array1 = np.allclose(A, B)
print(array1)

First array: [1 2 3 4 5]
Second array: [1 2 3 4 4]
Arrays equal or not-
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [35]:
import numpy as np
Vector=np.random.randint(10,size=(10))
print("Vector", Vector)
Vector[Vector.argmax()] = 0
print("Replacing maximum value by 0- ")
print(Vector)


Vector [0 0 0 7 3 5 2 7 5 3]
Replacing maximum value by 0- 
[0 0 0 0 3 5 2 7 5 3]


# 9. How to print all the values of an array?

In [45]:
import numpy as np
Array=np.arange(70)
np.set_printoptions(threshold=np.inf)
print(Array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


# 10.Subtract the mean of each row of a matrix

In [58]:
import numpy as np
print("Matrix-")
array = np.arange(25).reshape(5,5)
print(array)
print("Subtracting the mean of each row of the given matrix-")
Result = array - array.mean(axis=1, keepdims=True)
print(Result)

Matrix-
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Subtracting the mean of each row of the given matrix-
[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [74]:
Vector=np.random.randint(1,8,9)
print("Vector-", Vector)
Vector2=np.random.randint(Vector)
print("Vector 2-", Vector2)
Vector2.sort()
a=[]
for i in Vector2:
    if i not in a:
        a.append(i)
for j in Vector:
    Vector[j] += 1

print("Indexing vector:", Vector2)
print("Result:",Vector)

Vector- [5 6 4 6 5 2 5 5 5]
Vector 2- [2 3 0 4 4 1 3 4 3]
Indexing vector: [0 1 2 3 3 3 4 4 4]
Result: [5 6 4 7 6 4 9 5 6]


# 12.How to get the diagonal of a dot product?

In [77]:
X = [[1,2],[3,4]]
Y = [[1,2],[3,4]]
Z = np.diag(np.dot(X,Y))
Z

array([ 7, 22])

# 13.How to find the most frequent value in an array?

In [93]:
import numpy as np
Array= np.random.randint(0,10,15)
print("Array-", Array)
print("Most frequent value in the Array-")
print(np.bincount(Array).argmax())

Array- [1 5 9 7 3 5 0 3 8 8 2 2 5 8 0]
Most frequent value in the Array-
5


# 14.How to get the n largest values of an array

In [99]:
import numpy as np
Array = np.arange(20)
print("Array-")
print(Array)
n = 1
print("Largest value of the Array is-")
result=Array[np.argsort(Array)[-n:]]
print(result)

Array-
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Largest value of the Array is-
[19]


# 15.How to create a record array from a regular array?

In [105]:
import numpy as np
Array1=np.array(['1','2','3','4'])
Array2=np.array(['One','Two','Three','Four'])
result= np.core.records.fromarrays([Array1, Array2])
print(result[0])
print(result[1])
print(result[2])

('1', 'One')
('2', 'Two')
('3', 'Three')
